version: "3"

services:
  redis:
    image: redis:alpine
    container_name: "app_redis"
    ports:
      - "6379:6379"
    networks:
      - app
  people-finder:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/people-finder
    networks:
      - app
    depends_on:
      - redis

networks:
  app:
    driver: bridge
